name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libsndfile
      run: sudo apt-get install -y libsndfile1-dev
    - name: make file-qdsp
      run: make file-qdsp
    - name: Install python packages
      run: pip install numpy && pip install scipy && pip install soundfile
    - name: make test
      run: make test
